"""
Astro K — PDF export via fpdf2.
Generates a tabular summary into io.BytesIO. Never writes to disk.
"""

from fpdf import FPDF
import io


def generate_chart_pdf(chart_data: dict) -> bytes:
    """
    Generate a PDF report from chart data.

    Args:
        chart_data: dict matching ChartResponse schema

    Returns:
        PDF file as bytes (ready for HTTP response)
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # --- Title ---
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(75, 75, 75)
    pdf.cell(0, 15, "Astro K - Vedic Birth Chart", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # --- Birth Data Header ---
    meta = chart_data["metadata"]
    loc = meta["user_location"]

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 6, f"Calculation Engine: {meta['calculation_engine']}  |  Ayanamsa: {meta['ayanamsa']}  |  Julian Day: {meta['julian_day']}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 6, f"Location: {loc['lat']:.4f}N, {loc['lon']:.4f}E  |  Timezone: {loc['tz']}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # --- Ascendant ---
    asc = chart_data["ascendant"]
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(50, 50, 50)
    pdf.cell(0, 8, f"Ascendant (Lagna): {asc['sign_name']} {asc['sign_degree']:.2f}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # --- Planetary Positions Table ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "Planetary Positions", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Table header
    col_widths = [25, 30, 35, 25, 35, 20, 20]
    headers = ["Planet", "Sign", "Degree", "Abs Deg", "Nakshatra", "Pada", "Retro"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 240, 240)
    pdf.set_draw_color(200, 200, 200)

    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 7, header, border=1, fill=True, align="C")
    pdf.ln()

    # Table rows
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)

    for planet in chart_data["planets"]:
        cells = [
            planet["id"].upper(),
            planet["sign_name"],
            f"{planet['sign_degree']:.2f}",
            f"{planet['absolute_degree']:.2f}",
            str(planet["nakshatra_index"]),
            str(planet["nakshatra_pada"]),
            "R" if planet["is_retrograde"] else "-",
        ]
        for i, cell in enumerate(cells):
            pdf.cell(col_widths[i], 6, cell, border=1, align="C")
        pdf.ln()

    pdf.ln(5)

    # --- House Cusps Table ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "House Cusps (Whole-Sign)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    house_col_widths = [30, 40]
    house_headers = ["House", "Sign"]

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(240, 240, 240)
    for i, header in enumerate(house_headers):
        pdf.cell(house_col_widths[i], 7, header, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(60, 60, 60)
    for house in chart_data["houses"]:
        pdf.cell(house_col_widths[0], 6, str(house["house_number"]), border=1, align="C")
        pdf.cell(house_col_widths[1], 6, house["sign_name"], border=1, align="C")
        pdf.ln()

    pdf.ln(8)

    # --- Footer ---
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 5, "Generated by Astro K | Privacy-first ephemeral chart engine | No data stored", align="C")

    # Output as bytes — never touches disk
    return pdf.output()
